# port of the application.
server:
  port: 7070
  
# Set profile and JPA HSQL configuration.
#spring:
#  application:
#    name: FARApp-Service
#  jpa: 
#    database: MYSQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource: 
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fardb
#    username: root
#    password: root
spring:
  application:
    name: FARApp
  jpa: 
    database: HSQL
    hibernate:
      ddl-auto: update
  datasource: 
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password: 
    url: jdbc:hsqldb:file:database/demo/farDB.db
    
# logging support.    
logging: 
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN